### ISSUE TITLE
TASK: 调研 userapps

### ISSUE THREAD

**Issue by unicornx** [unicornx/rt-thread#1]
背景 ： <https://github.com/RT-Thread/rt-thread/issues/9623>

要求：调研 <https://github.com/RT-Thread/userapps.git> 理解改项目的功能，使用技术，基本设计思想

输出：
- 最好能基于一个开发板 virt 的也可以上的 RTT smart 跑一个 demo 出来
- 准备一个时长 30 分钟左右的讲解（包括 ppt），介绍 userapps。

完成时间：11 月 13 日前完成

**Comment by koikky** [comment]
好的

**Comment by unicornx** [comment]
close。不再 track
