### ISSUE TITLE
TASK: 调研 milkv duo sdk

### ISSUE THREAD

**Issue by unicornx** [unicornx/rt-thread#2]
背景 ： <https://github.com/RT-Thread/rt-thread/issues/9623>

要求，调研 <https://github.com/milkv-duo/duo-buildroot-sdk>，理解针对 [milkv duo](https://milkv.io/duo) 的构建过程

输出：准备一个时长 30 分钟左右的讲解（包括ppt），介绍 sdk 中构建步骤和细节。

完成时间：11 月 11 日前完成

参考：<https://gitee.com/unicornx/tblog/blob/master/articles/20240329-duo-bootflow.md>

**Comment by jojoandgyc** [comment]
accept

**Comment by unicornx** [comment]
close 不再 track
