### ISSUE TITLE
TASK: 为 bm4duo 移植 duoS

### ISSUE THREAD

**Issue by unicornx** [unicornx/rt-thread#3]
背景：为 <https://github.com/RT-Thread/rt-thread/issues/9623> 做准备

要求：了解 <https://github.com/unicornx/bm4duo>, 该项目目前只支持了 duo 和 duo256，添加支持 duo S

输出：提交代码，支持 duo S。

完成时间：11 月 16 日

**Comment by jiuyueshenhua** [comment]
能分配给我吗？

**Comment by unicornx** [comment]
close。不再 track
