### ISSUE TITLE
TASK: 为 duo 产品的 smart 开发 sdk

### ISSUE THREAD

**Issue by unicornx** [unicornx/rt-thread#4]
任务背景 ：<https://github.com/RT-Thread/rt-thread/issues/9623>

任务描述：这是一个内部的研究项目，具体目标参考 ”任务背景“。

注意事项，由于目前 RT-smart 针对 duo 还不完善，具体参考 <https://github.com/RT-Thread/rt-thread/issues/9622>。目前 RTT 对 duo 已经支持了 RT-standard 版本，可以先拿 RT-standard 为基础先做起来。

RTT 上 duo 的 bsp 路径是 `bsp/cvitek`
![c0976b3b63ff6a22ae1bb2ed09d7ba1](https://github.com/user-attachments/assets/43240aa7-2e2d-4497-8a64-ac6e7012a042)
我们只考虑 riscv 的 c906_little (c906 小核) 和 cv18xx_risc-v (c906 大核)，暂不考虑 ARM 的核。

这个内部任务目前请三位同学都尝试做一下，按开发板分：

- 黄云展：duo
- 欧阳兴铖：duo256
- 刘康冰：duo-S

大家各自自己设计，最后 pk 一下哪个方案好。

**Comment by koikky** [comment]
好的

**Comment by jiuyueshenhua** [comment]
收到。

**Comment by jojoandgyc** [comment]
Accept

**Comment by unicornx** [comment]
moved to https://github.com/plctlab/plct-rt-thread/issues/1 , close this issue
