### ISSUE TITLE
关于duo sdk仓库的疑惑。

### ISSUE THREAD

**Issue by jiuyueshenhua** [unicornx/rt-thread#5]
# 背景
目的：完成#3 issue

# 已知

sdk处理第三方库依赖的方式是把第三方的源码拉到本地，自己编译。

生成uboot和linux内核的调用链：

![image.png](https://tc-cdn.flowus.cn/oss/9c258b2d-7ca7-4c32-807d-177844a2e955/image.png?time=1731376800&token=a5837ef1a097661ecd70075c443c1463b7f555b1d644b0f764a652e45f90049d&role=free)

# 未知

1. 已经知道了脚本中生成uboot和linux内核的过程，但不清楚fip.bin其他部分如何生成的。也就是FSBL到AR param这一部分。

![image.png](https://tc-cdn.flowus.cn/oss/17a18f48-fbde-45dc-97f1-d001bf099465/image.png?time=1731376800&token=ca55f33e49d864391e130dfa71cffc1bbf117bab1a032290710baf506589d540&role=free)

我的目的是让bmforduo支持duo s，需要移植sdk的一部分到仓库的prebuild目录。

但我不知道prebuild的bl2.bin，也就是FSBL，在duo sdk里是如何生成的。
而且fip.bin的freertos部分有对应的脚本函数，但未被调用。

![image.png](https://tc-cdn.flowus.cn/oss/15cd8b13-fa12-4ce2-874d-14eaf6197154/image.png?time=1731376800&token=683cdfe76aa29fc0aba560929fe6bbaa0295fd0d3e2570ab19afca0b548afb71&role=free)

2. 我还是不太明白如何要从脚本里裁剪出prebuild目录对应的三个文件，写新脚本调用脚本里的函数的吗？

**Comment by unicornx** [comment]
可以注意看一下目前 RTT 中针对 bsp/cvitek 的打包处理。特别是  bsp/cvitek/combine-fip.sh 和 bsp/cvitek/mksdimg.sh，应该就回答了你的问题，rtt 里的 cvitek_bootloader 实际上就是把 milkv duosdk 里的相关目录和文件抽出来的，构建的机制是一样的

u-boot 和 linux 这些组件具体是怎么做的，其实不是我们这次关注的重点，linux 会被 rtt 代替，而 u-boot/opensbi/fsbl 这些我的想法是最后对于我们最后打包也就是个 prebuild 的概念。关键是要搞清楚 fip.bin 是怎么做出来的

**Comment by unicornx** [comment]
没有问题 我就 close 这个 issue 了？
